### ISSUE TITLE
demo docs

### ISSUE THREAD

**Issue by dzaal** [PitPik/tinyDatePicker#1]
your demo page sucks.
Need to be a hardcore coder to understand what you do with the options, you dont mention how this is going with the 4 css files, too bad this isnt working out of the box because the specs are very promising, I have to find myself another one. 
- make one css file, and mention it.
- seperate all your examples in different bare bone html pages

**Comment by PitPik** [comment]
Hoi @dzaal,
tinyDatePicker is very new (5 days) and I could hardly publish it because I don't have that much time to write demos and documentation. The demo page is a collection of some of my tests.
This project is 'in progress' and not 'done' yet (that's also why I put it on gitHub so people can participate and help finishing if they like to).

For now, I prepared a plain version for you so you can see where to start from, a 'naked' version with only some necessary stylings: http://www.dematte.at/tinyDatePicker/naked/

Groetjes

**Comment by PitPik** [comment]
Hi @dzaal ,
I added another clean boilerplate example in http://www.dematte.at/tinyDatePicker/white/ or in the project at ./white/
...and I updated the documentation a bit.

Maybe that helps you to understand

**Comment by PitPik** [comment]
The 'white' demo is so simple now,... that I will close this issue ;o)

**Comment by dzaal** [comment]
better!

thank you
